/**
 * ARI Cognitive Knowledge Sources
 *
 * Curated sources for LOGOS/ETHOS/PATHOS frameworks.
 * Each source is tagged with:
 * - Council members who benefit
 * - Frameworks it supports
 * - Trust level and update frequency
 * - Sample insights for integration
 *
 * @module cognition/knowledge/cognitive-sources
 */

import type { KnowledgeSource } from '../types.js';

/**
 * The 35+ curated knowledge sources for ARI's cognitive layer.
 * Covers all frameworks across LOGOS, ETHOS, and PATHOS.
 */
export const COGNITIVE_KNOWLEDGE_SOURCES: KnowledgeSource[] = [
  // =============================================================================
  // LOGOS SOURCES — REASON & CALCULATION
  // =============================================================================

  {
    id: 'bayesian-lesswrong',
    name: 'LessWrong Sequences - Bayesian Reasoning',
    url: 'https://www.lesswrong.com/rationality',
    category: 'RESEARCH',
    trustLevel: 'VERIFIED',
    pillar: 'LOGOS',
    councilMembers: ['risk_assessor', 'planner', 'ethics', 'integrator'],
    frameworks: ['Bayesian Reasoning'],
    updateFrequency: 'weekly',
    contentType: 'article',
    keyTopics: ['probability', 'belief updating', 'rationality', 'evidence evaluation'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Strong evidence should shift beliefs proportionally to likelihood ratios',
      'Conservation of expected evidence: expected posterior equals prior',
    ],
    enabled: true,
  },

  {
    id: 'signal-noise-silver',
    name: 'The Signal and the Noise by Nate Silver',
    url: 'https://en.wikipedia.org/wiki/The_Signal_and_the_Noise',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'LOGOS',
    councilMembers: ['risk_assessor', 'planner', 'wealth'],
    frameworks: ['Bayesian Reasoning', 'Expected Value'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['forecasting', 'prediction', 'uncertainty', 'statistical thinking'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Distinguishing signal from noise requires probabilistic thinking',
      'Foxes (many models) outperform hedgehogs (one big idea) in forecasting',
    ],
    enabled: true,
  },

  {
    id: 'thinking-systems-meadows',
    name: 'Thinking in Systems by Donella Meadows',
    url: 'https://en.wikipedia.org/wiki/Thinking_In_Systems:_A_Primer',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'LOGOS',
    councilMembers: ['planner', 'integrator', 'resource_manager', 'wellness'],
    frameworks: ['Systems Thinking'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['feedback loops', 'leverage points', 'system archetypes', 'delays'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'The 12 leverage points range from parameters (low leverage) to paradigm shifts (high leverage)',
      'Delays in feedback loops cause overshoot and instability',
    ],
    enabled: true,
  },

  {
    id: 'antifragile-taleb',
    name: 'Antifragile by Nassim Taleb',
    url: 'https://en.wikipedia.org/wiki/Antifragile_(book)',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'LOGOS',
    councilMembers: ['risk_assessor', 'wealth', 'planner', 'wellness'],
    frameworks: ['Antifragility'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['optionality', 'convexity', 'barbell strategy', 'via negativa'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Antifragile systems gain from disorder and volatility',
      'Convex exposure (limited downside, unlimited upside) builds antifragility',
    ],
    enabled: true,
  },

  {
    id: 'kelly-criterion-poundstone',
    name: "Fortune's Formula by William Poundstone",
    url: 'https://en.wikipedia.org/wiki/Fortune%27s_Formula',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'LOGOS',
    councilMembers: ['wealth', 'risk_assessor', 'resource_manager'],
    frameworks: ['Kelly Criterion'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['position sizing', 'edge', 'bankroll management', 'risk of ruin'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Kelly sizing maximizes long-term growth rate',
      'Fractional Kelly (half or quarter) reduces volatility while preserving most growth',
    ],
    enabled: true,
  },

  {
    id: 'decision-analysis-howard',
    name: "Ron Howard's Decision Analysis Research",
    url: 'https://www.sdg.com/decision-analysis/',
    category: 'RESEARCH',
    trustLevel: 'VERIFIED',
    pillar: 'LOGOS',
    councilMembers: ['planner', 'risk_assessor', 'integrator'],
    frameworks: ['Decision Trees', 'Expected Value'],
    updateFrequency: 'monthly',
    contentType: 'paper',
    keyTopics: ['decision trees', 'influence diagrams', 'value of information', 'sensitivity analysis'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Backward induction reveals optimal paths through decision trees',
      'Value of information quantifies the benefit of gathering more data',
    ],
    enabled: true,
  },

  {
    id: 'skin-game-taleb',
    name: 'Skin in the Game by Nassim Taleb',
    url: 'https://en.wikipedia.org/wiki/Skin_in_the_Game_(book)',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'LOGOS',
    councilMembers: ['ethics', 'risk_assessor', 'wealth', 'guardian'],
    frameworks: ['Antifragility', 'Risk Assessment'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['asymmetry', 'incentives', 'risk sharing', 'agency problem'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Symmetry in risk and reward aligns incentives',
      'Never trust advice from someone who does not have skin in the game',
    ],
    enabled: true,
  },

  {
    id: 'five-rings-musashi',
    name: 'The Book of Five Rings by Miyamoto Musashi',
    url: 'https://en.wikipedia.org/wiki/The_Book_of_Five_Rings',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'LOGOS',
    councilMembers: ['guardian', 'planner', 'executor', 'ethics'],
    frameworks: ['Strategic Thinking'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['strategy', 'perception', 'timing', 'adaptation', 'simplicity'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Perceive things truly: see the essence, not the surface',
      'The way of strategy is the way of nature',
    ],
    enabled: true,
  },

  {
    id: 'superforecasting-tetlock',
    name: 'Superforecasting by Philip Tetlock',
    url: 'https://en.wikipedia.org/wiki/Superforecasting',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'LOGOS',
    councilMembers: ['risk_assessor', 'planner', 'integrator'],
    frameworks: ['Bayesian Reasoning', 'Expected Value'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['forecasting', 'calibration', 'granular probabilities', 'base rates'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Superforecasters update beliefs incrementally based on new evidence',
      'Using outside view (base rates) before inside view improves forecasts',
    ],
    enabled: true,
  },

  {
    id: 'black-swan-taleb',
    name: 'The Black Swan by Nassim Taleb',
    url: 'https://en.wikipedia.org/wiki/The_Black_Swan_(Taleb_book)',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'LOGOS',
    councilMembers: ['risk_assessor', 'planner', 'guardian'],
    frameworks: ['Risk Assessment', 'Antifragility'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['tail risk', 'unknown unknowns', 'narrative fallacy', 'mediocristan vs extremistan'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Black swan events are rare, high-impact, and retrospectively predictable',
      'Focus on robustness to negative black swans and exposure to positive ones',
    ],
    enabled: true,
  },

  // =============================================================================
  // ETHOS SOURCES — CHARACTER & DISCIPLINE
  // =============================================================================

  {
    id: 'thinking-fast-slow-kahneman',
    name: 'Thinking, Fast and Slow by Daniel Kahneman',
    url: 'https://en.wikipedia.org/wiki/Thinking,_Fast_and_Slow',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'ETHOS',
    councilMembers: ['ethics', 'risk_assessor', 'guardian', 'integrator'],
    frameworks: ['Cognitive Bias Detection'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['system 1 and 2', 'heuristics', 'biases', 'prospect theory', 'overconfidence'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'System 1 is fast and automatic but prone to biases',
      'Loss aversion causes people to weigh losses ~2x more than equivalent gains',
    ],
    enabled: true,
  },

  {
    id: 'nudge-thaler',
    name: 'Nudge by Richard Thaler',
    url: 'https://en.wikipedia.org/wiki/Nudge_(book)',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'ETHOS',
    councilMembers: ['ethics', 'wellness', 'growth', 'relationships'],
    frameworks: ['Cognitive Bias Detection', 'Behavioral Design'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['choice architecture', 'defaults', 'behavioral economics', 'libertarian paternalism'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Default options dramatically influence choices',
      'Small nudges can produce large behavioral changes',
    ],
    enabled: true,
  },

  {
    id: 'emotional-intelligence-goleman',
    name: 'Emotional Intelligence by Daniel Goleman',
    url: 'https://en.wikipedia.org/wiki/Emotional_Intelligence_(book)',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'ETHOS',
    councilMembers: ['wellness', 'relationships', 'guardian', 'ethics'],
    frameworks: ['Emotional State Assessment'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['self-awareness', 'self-regulation', 'empathy', 'social skills'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Emotional competencies are as important as IQ for success',
      'Self-awareness is the foundation of emotional intelligence',
    ],
    enabled: true,
  },

  {
    id: 'trading-zone-douglas',
    name: 'Trading in the Zone by Mark Douglas',
    url: 'https://www.amazon.com/Trading-Zone-Confidence-Discipline-Attitude/dp/0735201447',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'ETHOS',
    councilMembers: ['wealth', 'risk_assessor', 'wellness', 'guardian'],
    frameworks: ['Fear/Greed Cycle', 'Emotional State Assessment', 'Discipline'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['trading psychology', 'fear', 'greed', 'discipline', 'probabilistic thinking'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Fear of loss prevents traders from letting winners run',
      'Greed causes revenge trading after losses',
    ],
    enabled: true,
  },

  {
    id: 'predictably-irrational-ariely',
    name: 'Predictably Irrational by Dan Ariely',
    url: 'https://en.wikipedia.org/wiki/Predictably_Irrational',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'ETHOS',
    councilMembers: ['ethics', 'wealth', 'relationships', 'integrator'],
    frameworks: ['Cognitive Bias Detection'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['irrationality', 'anchoring', 'social norms', 'relativity'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Humans are systematically irrational in predictable ways',
      'Anchoring effects persist even when anchors are obviously irrelevant',
    ],
    enabled: true,
  },

  {
    id: 'influence-cialdini',
    name: 'Influence by Robert Cialdini',
    url: 'https://en.wikipedia.org/wiki/Influence:_Science_and_Practice',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'ETHOS',
    councilMembers: ['guardian', 'ethics', 'relationships', 'wealth'],
    frameworks: ['Bias Detection', 'Social Influence'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['reciprocity', 'commitment', 'authority', 'scarcity', 'social proof'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Six principles of influence: reciprocity, commitment, social proof, authority, liking, scarcity',
      'Awareness of influence tactics provides cognitive defense',
    ],
    enabled: true,
  },

  // =============================================================================
  // PATHOS SOURCES — GROWTH & WISDOM
  // =============================================================================

  {
    id: 'feeling-good-burns',
    name: 'Feeling Good by David Burns',
    url: 'https://en.wikipedia.org/wiki/Feeling_Good:_The_New_Mood_Therapy',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'PATHOS',
    councilMembers: ['wellness', 'growth', 'relationships', 'integrator'],
    frameworks: ['CBT Reframing'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['cognitive distortions', 'depression', 'mood', 'thought records', 'cognitive therapy'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Ten cognitive distortions underlie most negative mood states',
      'Thought records help identify and challenge distorted thinking',
    ],
    enabled: true,
  },

  {
    id: 'beck-institute',
    name: 'Beck Institute for Cognitive Behavior Therapy',
    url: 'https://beckinstitute.org/',
    category: 'DOCUMENTATION',
    trustLevel: 'VERIFIED',
    pillar: 'PATHOS',
    councilMembers: ['wellness', 'growth', 'integrator'],
    frameworks: ['CBT Reframing'],
    updateFrequency: 'monthly',
    contentType: 'documentation',
    keyTopics: ['CBT techniques', 'cognitive restructuring', 'behavioral activation', 'evidence-based therapy'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'CBT is the gold standard for treating depression and anxiety',
      'Identify automatic thoughts, evaluate evidence, generate alternative interpretations',
    ],
    enabled: true,
  },

  {
    id: 'meditations-aurelius',
    name: 'Meditations by Marcus Aurelius',
    url: 'https://en.wikipedia.org/wiki/Meditations',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'PATHOS',
    councilMembers: ['ethics', 'wellness', 'growth', 'guardian'],
    frameworks: ['Stoic Philosophy', 'Dichotomy of Control', 'Virtue Ethics'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['stoicism', 'virtue', 'control', 'acceptance', 'duty'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Focus only on what is within your control',
      'The obstacle is the way: challenges are opportunities for virtue',
    ],
    enabled: true,
  },

  {
    id: 'enchiridion-epictetus',
    name: 'Enchiridion by Epictetus',
    url: 'https://en.wikipedia.org/wiki/Enchiridion_of_Epictetus',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'PATHOS',
    councilMembers: ['ethics', 'wellness', 'growth'],
    frameworks: ['Dichotomy of Control', 'Stoic Philosophy'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['dichotomy of control', 'indifference', 'judgment', 'tranquility'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Some things are up to us, some are not — focus only on the former',
      'It is not things that disturb us, but our judgments about things',
    ],
    enabled: true,
  },

  {
    id: 'daily-stoic-holiday',
    name: 'The Daily Stoic by Ryan Holiday',
    url: 'https://en.wikipedia.org/wiki/Ryan_Holiday',
    category: 'BOOK',
    trustLevel: 'STANDARD',
    pillar: 'PATHOS',
    councilMembers: ['wellness', 'growth', 'ethics'],
    frameworks: ['Stoic Philosophy', 'Virtue Ethics'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['stoicism', 'daily practice', 'virtue', 'resilience'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Daily reflection builds stoic practice',
      'Amor fati: love your fate, embrace what happens',
    ],
    enabled: true,
  },

  {
    id: 'peak-ericsson',
    name: 'Peak by Anders Ericsson',
    url: 'https://en.wikipedia.org/wiki/Peak:_Secrets_from_the_New_Science_of_Expertise',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'PATHOS',
    councilMembers: ['growth', 'creative', 'planner', 'integrator'],
    frameworks: ['Deliberate Practice'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['deliberate practice', 'skill acquisition', 'expertise', 'mental representations'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Deliberate practice requires focused attention, immediate feedback, and progressive difficulty',
      'Natural talent is overrated; structured practice builds expertise',
    ],
    enabled: true,
  },

  {
    id: 'almanack-naval',
    name: 'The Almanack of Naval Ravikant by Eric Jorgenson',
    url: 'https://www.navalmanack.com/',
    category: 'BOOK',
    trustLevel: 'STANDARD',
    pillar: 'PATHOS',
    councilMembers: ['wealth', 'growth', 'wellness', 'creative'],
    frameworks: ['Wisdom', 'Leverage', 'Mental Models'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['wealth creation', 'leverage', 'specific knowledge', 'happiness', 'mental models'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Seek wealth, not money or status',
      'Learn to sell, learn to build; if you can do both, you are unstoppable',
    ],
    enabled: true,
  },

  {
    id: 'principles-dalio',
    name: 'Principles by Ray Dalio',
    url: 'https://en.wikipedia.org/wiki/Principles_(book)',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'PATHOS',
    councilMembers: ['wealth', 'growth', 'planner', 'integrator', 'ethics'],
    frameworks: ['Wisdom', 'Systems Thinking', 'Reflection'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['radical transparency', 'idea meritocracy', 'principles', 'pain + reflection = progress'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Pain + Reflection = Progress',
      'Radical transparency and idea meritocracy produce better decisions',
    ],
    enabled: true,
  },

  {
    id: 'poor-charlies-munger',
    name: "Poor Charlie's Almanack by Charlie Munger",
    url: 'https://en.wikipedia.org/wiki/Charlie_Munger',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'PATHOS',
    councilMembers: ['wealth', 'growth', 'ethics', 'integrator'],
    frameworks: ['Mental Models', 'Wisdom', 'Inversion'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['mental models', 'latticework', 'inversion', 'multidisciplinary thinking'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Develop a latticework of mental models from multiple disciplines',
      'Invert, always invert: solve problems backward',
    ],
    enabled: true,
  },

  // =============================================================================
  // CROSS-CUTTING SOURCES
  // =============================================================================

  {
    id: 'farnam-street',
    name: 'Farnam Street',
    url: 'https://fs.blog/',
    category: 'DOCUMENTATION',
    trustLevel: 'VERIFIED',
    pillar: 'CROSS_CUTTING',
    councilMembers: ['integrator', 'growth', 'ethics', 'planner'],
    frameworks: ['Mental Models', 'Decision Making', 'Systems Thinking'],
    updateFrequency: 'weekly',
    contentType: 'article',
    keyTopics: ['mental models', 'decision making', 'systems thinking', 'wisdom'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'Mental models are how we understand the world',
      'Second-order thinking considers consequences of consequences',
    ],
    enabled: true,
  },

  {
    id: '80000-hours',
    name: '80,000 Hours Research',
    url: 'https://80000hours.org/',
    category: 'RESEARCH',
    trustLevel: 'VERIFIED',
    pillar: 'CROSS_CUTTING',
    councilMembers: ['growth', 'ethics', 'planner', 'wealth'],
    frameworks: ['Expected Value', 'Decision Making', 'Career Strategy'],
    updateFrequency: 'monthly',
    contentType: 'article',
    keyTopics: ['career capital', 'impact', 'effective altruism', 'career strategy'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Build career capital early, then deploy it for high-impact work',
      'Consider scale, neglectedness, and tractability when choosing problems',
    ],
    enabled: true,
  },

  {
    id: 'anthropic-docs',
    name: 'Anthropic Documentation',
    url: 'https://docs.anthropic.com/',
    category: 'OFFICIAL',
    trustLevel: 'VERIFIED',
    pillar: 'CROSS_CUTTING',
    councilMembers: ['integrator', 'guardian', 'executor', 'ethics'],
    frameworks: ['AI Reasoning', 'Cognitive Architecture'],
    updateFrequency: 'weekly',
    contentType: 'documentation',
    keyTopics: ['claude', 'prompting', 'AI safety', 'reasoning', 'constitutional AI'],
    integrationPriority: 'HIGH',
    securityNotes: 'Official Anthropic documentation — authoritative source for Claude capabilities',
    sampleInsights: [
      'Claude uses constitutional AI with explicit values and constraints',
      'Extended thinking improves complex reasoning tasks',
    ],
    enabled: true,
  },

  {
    id: 'lesswrong-rationality',
    name: 'LessWrong Rationality A-Z',
    url: 'https://www.lesswrong.com/rationality',
    category: 'RESEARCH',
    trustLevel: 'VERIFIED',
    pillar: 'CROSS_CUTTING',
    councilMembers: ['integrator', 'ethics', 'growth', 'risk_assessor'],
    frameworks: ['Rationality', 'Bayesian Reasoning', 'Cognitive Biases'],
    updateFrequency: 'weekly',
    contentType: 'article',
    keyTopics: ['rationality', 'epistemic hygiene', 'map and territory', 'reductionism'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'The map is not the territory',
      'Update incrementally on evidence; avoid binary thinking',
    ],
    enabled: true,
  },

  {
    id: 'cognitive-biases-codex',
    name: 'Cognitive Biases Codex',
    url: 'https://en.wikipedia.org/wiki/List_of_cognitive_biases',
    category: 'DOCUMENTATION',
    trustLevel: 'STANDARD',
    pillar: 'CROSS_CUTTING',
    councilMembers: ['ethics', 'guardian', 'risk_assessor', 'integrator'],
    frameworks: ['Cognitive Bias Detection'],
    updateFrequency: 'monthly',
    contentType: 'documentation',
    keyTopics: ['cognitive biases', 'heuristics', 'systematic errors', 'debiasing'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Humans exhibit ~100+ documented cognitive biases',
      'Awareness of biases is necessary but not sufficient for debiasing',
    ],
    enabled: true,
  },

  // =============================================================================
  // ADDITIONAL HIGH-VALUE SOURCES
  // =============================================================================

  {
    id: 'rationality-eliezer',
    name: 'Rationality: From AI to Zombies by Eliezer Yudkowsky',
    url: 'https://intelligence.org/rationality-ai-zombies/',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'CROSS_CUTTING',
    councilMembers: ['integrator', 'ethics', 'guardian', 'growth'],
    frameworks: ['Rationality', 'Bayesian Reasoning', 'Bias Detection'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['rationality', 'AI', 'decision theory', 'reductionism', 'mysterious answers'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Mysterious answers are not explanations',
      'Guard against privileging the hypothesis',
    ],
    enabled: true,
  },

  {
    id: 'scout-mindset-galef',
    name: 'The Scout Mindset by Julia Galef',
    url: 'https://en.wikipedia.org/wiki/Julia_Galef',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'ETHOS',
    councilMembers: ['ethics', 'risk_assessor', 'guardian', 'integrator'],
    frameworks: ['Rationality', 'Bias Detection'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['scout vs soldier mindset', 'truth-seeking', 'motivated reasoning', 'intellectual honesty'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Scout mindset seeks truth; soldier mindset defends beliefs',
      'Intellectual honesty requires curiosity and willingness to be wrong',
    ],
    enabled: true,
  },

  {
    id: 'alignment-problem-christian',
    name: 'The Alignment Problem by Brian Christian',
    url: 'https://en.wikipedia.org/wiki/The_Alignment_Problem',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'CROSS_CUTTING',
    councilMembers: ['guardian', 'ethics', 'integrator'],
    frameworks: ['AI Safety', 'Value Alignment'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['AI safety', 'value alignment', 'machine learning', 'ethics', 'fairness'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'AI systems inherit human biases from training data',
      'Value alignment is a technical and philosophical challenge',
    ],
    enabled: true,
  },

  {
    id: 'algorithms-live-christian',
    name: 'Algorithms to Live By by Brian Christian',
    url: 'https://en.wikipedia.org/wiki/Algorithms_to_Live_By',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'LOGOS',
    councilMembers: ['planner', 'scheduler', 'resource_manager', 'integrator'],
    frameworks: ['Decision Theory', 'Optimization'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['algorithms', 'optimal stopping', 'explore-exploit', 'caching', 'scheduling'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      '37% rule for optimal stopping (e.g., hiring, apartment hunting)',
      'Explore-exploit tradeoff: balance learning and earning',
    ],
    enabled: true,
  },

  {
    id: 'atomic-habits-clear',
    name: 'Atomic Habits by James Clear',
    url: 'https://en.wikipedia.org/wiki/Atomic_Habits',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'PATHOS',
    councilMembers: ['growth', 'wellness', 'scheduler', 'integrator'],
    frameworks: ['Habit Formation', 'Behavior Change'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['habits', 'behavior change', 'systems', 'identity', 'environment design'],
    integrationPriority: 'HIGH',
    sampleInsights: [
      'You do not rise to the level of your goals; you fall to the level of your systems',
      'Habit stacking: link new habits to existing triggers',
    ],
    enabled: true,
  },

  {
    id: 'deep-work-newport',
    name: 'Deep Work by Cal Newport',
    url: 'https://en.wikipedia.org/wiki/Cal_Newport',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'PATHOS',
    councilMembers: ['growth', 'scheduler', 'wellness', 'creative'],
    frameworks: ['Focus', 'Productivity'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['deep work', 'focus', 'attention', 'productivity', 'distraction'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Deep work is rare, valuable, and meaningful',
      'Attention residue: switching tasks leaves cognitive residue that impairs performance',
    ],
    enabled: true,
  },

  {
    id: 'designing-your-life',
    name: 'Designing Your Life by Bill Burnett',
    url: 'https://en.wikipedia.org/wiki/Designing_Your_Life',
    category: 'BOOK',
    trustLevel: 'VERIFIED',
    pillar: 'PATHOS',
    councilMembers: ['growth', 'creative', 'planner', 'wellness'],
    frameworks: ['Design Thinking', 'Prototyping'],
    updateFrequency: 'static',
    contentType: 'book',
    keyTopics: ['design thinking', 'prototyping', 'career', 'life design', 'iteration'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Prototype your way forward: test ideas cheaply before committing',
      'Reframe problems: shift from "What should I do?" to "What could I try?"',
    ],
    enabled: true,
  },

  {
    id: 'stanford-decision-analysis',
    name: 'Stanford Decision Analysis Group',
    url: 'https://sdg.stanford.edu/',
    category: 'RESEARCH',
    trustLevel: 'VERIFIED',
    pillar: 'LOGOS',
    councilMembers: ['planner', 'risk_assessor', 'integrator'],
    frameworks: ['Decision Analysis', 'Decision Trees'],
    updateFrequency: 'monthly',
    contentType: 'paper',
    keyTopics: ['decision quality', 'decision analysis', 'framing', 'alternatives', 'value of information'],
    integrationPriority: 'MEDIUM',
    sampleInsights: [
      'Six elements of decision quality: frame, alternatives, information, values, reasoning, commitment',
      'Good decisions are not judged by outcomes, but by process',
    ],
    enabled: true,
  },
];
