/**
 * ARI Obsidian Context Pack — CONTEXT_PACK.md + WORKING_SET.md generation.
 */

import { getOpenLoops, getVaultStats, getVaultDb } from "./vault-index.js";
import { writeVaultFile, readVaultFile, vaultFileExists, newTraceHex } from "./vault-manager.js";

function readFileIfExists(relPath: string): string {
  try {
    return vaultFileExists(relPath) ? readVaultFile(relPath) : "";
  } catch {
    return "";
  }
}

function summarize(content: string, maxChars = 300): string {
  if (!content) {
    return "";
  }
  return content
    .slice(0, maxChars)
    .replace(/^---[\s\S]*?---\n/, "")
    .trim();
}

export function generateContextPack(): { contextPack: string; workingSet: string } {
  const today = new Date().toISOString().slice(0, 10);
  const traceId = newTraceHex();
  const stats = getVaultStats();
  const openLoops = getOpenLoops();

  // Read context OS files
  const identity = summarize(readFileIfExists("00-System/Identity.md"));
  const ruts = summarize(readFileIfExists("00-System/Ruts.md"));
  const calIntent = summarize(readFileIfExists("00-System/Calendar-Intent.md"));

  // Recent inbox items
  const db = getVaultDb();
  const recentCaptures = db
    .prepare(
      "SELECT path, title FROM notes WHERE note_type IN ('capture','interaction-fragment') ORDER BY last_indexed DESC LIMIT 5",
    )
    .all() as Array<{ path: string; title: string }>;

  // Active projects
  const activeProjects = db
    .prepare(
      "SELECT DISTINCT project FROM tasks WHERE status = 'open' AND project IS NOT NULL LIMIT 10",
    )
    .all() as Array<{ project: string }>;

  const contextPack = `---
type: context-pack
date: ${today}
source: ari-obsidian
trace_id: ${traceId}
tags: [context-pack, system]
---
# Context Pack — ${today}

## Identity
${identity || "_Not yet filled_"}

## This Week's Intent
${calIntent || "_Not yet filled_"}

## Active Projects
${activeProjects.map((p) => `- ${p.project}`).join("\n") || "_No active projects_"}

## Open Loops (${openLoops.length})
${
  openLoops
    .slice(0, 8)
    .map((l) => `- [[${l.path}]] — ${l.title || "untitled"}`)
    .join("\n") || "_None_"
}

## Recent Captures (Inbox)
${recentCaptures.map((c) => `- [[${c.path}]] — ${c.title || "untitled"}`).join("\n") || "_None_"}

## Known Ruts
${ruts || "_Not yet filled_"}

---
_Auto-generated by ari-obsidian at ${new Date().toISOString()}_
`;

  const workingSet = `---
type: working-set
date: ${today}
source: ari-obsidian
trace_id: ${traceId}
tags: [working-set, system]
---
# Working Set — ${today}

## Vault Stats
- Notes: ${stats.noteCount}
- Open loops: ${openLoops.length}

## Context References
- [[00-System/Identity]]
- [[00-System/Ruts]]
- [[00-System/Calendar-Intent]]

## Active Work
<!-- Populated from recent agent interactions -->

---
_Auto-generated by ari-obsidian at ${new Date().toISOString()}_
`;

  writeVaultFile("00-System/CONTEXT_PACK.md", contextPack);
  writeVaultFile("00-System/WORKING_SET.md", workingSet);
  writeVaultFile("00-System/Open-Loops-Dashboard.md", generateOpenLoopsDashboard(openLoops));

  return { contextPack, workingSet };
}

function generateOpenLoopsDashboard(
  openLoops: Array<{ path: string; title: string; last_indexed: string }>,
): string {
  const today = new Date().toISOString().slice(0, 10);
  const rows = openLoops
    .map((l) => {
      const ageDays = Math.floor((Date.now() - new Date(l.last_indexed).getTime()) / 86400000);
      return `| [[${l.path}]] | ${l.title || "untitled"} | ${ageDays}d |`;
    })
    .join("\n");

  return `---
type: working-set
date: ${today}
source: ari-obsidian
trace_id: manual
tags: [open-loops, dashboard]
---
# Open Loops Dashboard — ${today}

| Note | Title | Age |
|------|-------|-----|
${rows || "| — | No open loops | — |"}

_Regenerated each morning by context_pack_
`;
}
