/**
 * ARI Obsidian Digest — daily/weekly note generation.
 */

import { getOpenLoops, getVaultStats } from "./vault-index.js";
import { writeVaultFile, newTraceHex } from "./vault-manager.js";

export interface VaultSnapshot {
  date: string;
  noteCount: number;
  openLoops: number;
  themes: string[];
  questions: string[];
  relatedNotes: string[];
  lastDigest?: string;
  traceId: string;
}

function getWeekNumber(date: Date): string {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const weekNo = Math.ceil(((d.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
  return `${d.getUTCFullYear()}-W${String(weekNo).padStart(2, "0")}`;
}

export function generateDailyDigest(): VaultSnapshot {
  const today = new Date().toISOString().slice(0, 10);
  const traceId = newTraceHex();
  const stats = getVaultStats();
  const openLoops = getOpenLoops();

  const content = `---
type: daily
date: ${today}
source: ari-obsidian
trace_id: ${traceId}
tags: [daily, digest]
---
# Daily Note — ${today}

## 3 MITs Today
<!-- Generated by ari-obsidian task engine -->

## Morning Context
- **Vault notes**: ${stats.noteCount}
- **Open loops**: ${openLoops.length}
- **Generated**: ${new Date().toISOString()}

## Open Loops
${
  openLoops
    .slice(0, 5)
    .map((l) => `- [[${l.path}]] — ${l.title || "untitled"}`)
    .join("\n") || "_No open loops_"
}

## Notable Interactions
<!-- Auto-populated by ari-obsidian auto-capture -->

## End of Day
<!-- Fill in: wins, blockers, tomorrow's intent -->
`;

  writeVaultFile(`40-Logs/Daily/${today}.md`, content);

  return {
    date: today,
    noteCount: stats.noteCount,
    openLoops: openLoops.length,
    themes: [],
    questions: [],
    relatedNotes: [],
    traceId,
  };
}

export function generateWeeklyDigest(): VaultSnapshot {
  const now = new Date();
  const weekId = getWeekNumber(now);
  const traceId = newTraceHex();
  const stats = getVaultStats();
  const openLoops = getOpenLoops();

  const content = `---
type: weekly
date: ${now.toISOString().slice(0, 10)}
source: ari-obsidian
trace_id: ${traceId}
tags: [weekly, digest]
---
# Weekly Digest — ${weekId}

## Summary
- **Total vault notes**: ${stats.noteCount}
- **Open loops this week**: ${openLoops.length}

## Themes
<!-- Auto-populated from weekly capture review -->

## Wins
<!-- Fill in -->

## Open Loops (persistent)
${
  openLoops
    .slice(0, 10)
    .map((l) => `- [[${l.path}]] — ${l.title || "untitled"}`)
    .join("\n") || "_None_"
}

## Next Week's Focus
<!-- Fill in -->
`;

  writeVaultFile(`50-Logs/Weekly/${weekId}.md`, content);

  return {
    date: now.toISOString().slice(0, 10),
    noteCount: stats.noteCount,
    openLoops: openLoops.length,
    themes: [],
    questions: [],
    relatedNotes: [],
    traceId,
  };
}
